server:
  port: 8083 # Puerto para el servicio_flota

spring:
  application:
    name: servicio_flota
  
  datasource:
    # Estos valores son para correr en tu PC local (fuera de Docker).
    # Docker Compose los va a sobreescribir con "postgres-flota" al arrancar.
    url: jdbc:postgresql://localhost:5432/flota_db
    username: back-admin
    password: admin123
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  security:
    oauth2:
      resourceserver:
        jwt:
          # Docker Compose lo sobreescribe con "keycloak"
          issuer-uri: http://localhost:8080/realms/logistica-realm
  
  profiles:
    active: dev

# --- ESTA ES LA PARTE IMPORTANTE ---
# Configuraci√≥n de Swagger UI conectada a Keycloak
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    oauth:
      client-id: tpi-backend-client
      use-pkce-with-authorization-code-grant: true
      # ESTO ES CLAVE: No incluir client-secret
    oauth2-redirect-url: http://localhost:8083/swagger-ui/oauth2-redirect.html
  oauth2:
    authorization-url: http://localhost:8080/realms/logistica-realm/protocol/openid-connect/auth
    token-url: http://localhost:8080/realms/logistica-realm/protocol/openid-connect/token