server:
  port: 8081 # Puerto para el servicio_logistico

spring:
  application:
    name: servicio_logistico
  
  datasource:
    url: jdbc:postgresql://localhost:5432/logistica_db
    username: back-admin
    password: admin123
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/logistica-realm
  
  profiles:
    active: dev

# --- CONFIGURACIÓN DE MICROSERVICIOS ---
microservices:
  openrouteservice:
    base-url: "https://api.openrouteservice.org"
    api-key: "eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjkxMzMyZmRjYzYzODRkMDliODRhN2VmM2Q2MTI2NDljIiwiaCI6Im11cm11cjY0In0="

# Configuración de Swagger UI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    oauth:
      client-id: tpi-backend-client
      use-pkce-with-authorization-code-grant: true
    oauth2-redirect-url: http://localhost:8081/swagger-ui/oauth2-redirect.html
  oauth2:
    authorization-url: http://localhost:8080/realms/logistica-realm/protocol/openid-connect/auth
    token-url: http://localhost:8080/realms/logistica-realm/protocol/openid-connect/token